#!/usr/bin/env ansible-playbook
---
- name: configures Fish shell
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} state=present
      become: yes
      with_items:
        - fish

    # TODO: Does not work in playbook, since it asks for password confirmation
    # - name: set zsh as default shell
    #   shell: chsh -s /usr/bin/fish
